# Generated by Django 5.0.4 on 2024-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=200)),
                ('abrev', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
