# Generated by Django 5.0.4 on 2024-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tipoequipo_incidencia_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='esPatrimonizado',
            field=models.BooleanField(default=False),
        ),
    ]
