# Generated by Django 5.0.4 on 2024-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_equipo_espatrimonizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='estadoPatrimonio',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='descripcionCompra',
        ),
        migrations.AddField(
            model_name='equipo',
            name='codInterno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fechaPecosa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nroDocAdq',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nroSerie',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='equipo',
            name='regSiaf',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipoDocAdq',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codPatrimonial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='oficinaPatri',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsablePatri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
